/* 
 * File:    main.cpp
 * Author:  Uriel Salazar
 * Created: March 4, 2015, 10:29 AM
 * Purpose: 3rd Homework Problem
 */

//System Libraries
#include <iostream>
using namespace std;

//User Libraries

//Global Constants
unsigned char CNVPCNT=100;

//Function Prototypes

//Execution Begins Here!
int main(int argc, char** argv) {
    //Declare Variables
    float cTSales, nECDiv;
    unsigned char pECDiv;
    //Input assigned values
    cTSales=4.6e6f;//Company Total Sales
    pECDiv=62;//Percentage Generated by East Coast Division
    nECDiv=cTSales/static_cast<float>(CNVPCNT)*pECDiv;//Number Generated by East Coast Division
    //Output Everything
    cout<<"Total Amount Generated by the East Coast Division"<<endl;
    cout<<"Known/Given Values:"<<endl;
    cout<<"The Company's Total Sales = "<<cTSales<<endl;
    cout<<"Percentage generated by the East Coast Division = "
            <<static_cast<int>(pECDiv)<<"%"<<endl;
    cout<<"Calculated Values:"<<endl;
    cout<<"Number Generated by East Coast Division = "<<nECDiv<<endl;
    return 0;
}