/* 
 * File:    main.cpp
 * Author:  Uriel Salazar
 * Created: March 4, 2015, 10:29 AM
 * Purpose: 3rd Homework Problem (Sales Prediction)
 */

//System Libraries
#include <iostream>
using namespace std;

//User Libraries

//Global Constants
unsigned char CNVPCNT=1e2;

//Function Prototypes

//Execution Begins Here!
int main(int argc, char** argv) {
    //Declare Variables
    float cTSales, nECDiv;
    unsigned char pECDiv;
    //Input Assigned Values
    cTSales=4.6e6;//Company Total Sales
    pECDiv=6.2e1;//Percentage Generated by East Coast Division
    //Number Generated by East Coast Division
    nECDiv=cTSales/static_cast<float>(CNVPCNT)*pECDiv;
    //Output Everything
    cout<<"Total Amount Generated by the East Coast Division"<<endl;
    cout<<"Known/Given Values:"<<endl;
    cout<<"The Company's Total Sales = $"<<cTSales<<endl;
    cout<<"Percentage generated by the East Coast Division = "
            <<static_cast<float>(pECDiv)<<"%"<<endl;
    cout<<"Calculated Values:"<<endl;
    cout<<"Amont Generated by the East Coast Division = $"<<nECDiv<<endl;
    //Exit Stage Right!
    return 0;
}