/* 
 * File:    main.cpp
 * Author:  rcc
 * Created: March 4, 2015, 10:29 AM
 * Purpose: 3rd Homework Problem
 */

//System Libraries
#include <iostream>
using namespace std;

//User Libraries

//Global Constants
unsigned char CNVPCNT=100;

//Function Prototypes

//Execution Begins Here!
int main(int argc, char** argv) {
        //Declare Variables
    unsigned short cTSales, nECDiv;
    unsigned char pECDiv;
    //Input assigned values
    cTSales=4.6e6f;//Company Total Sales
    pECDiv=62;//Percentage Generated by East Coast Division
    nECDiv=cTSales/static_cast<float>(CNVPCNT)
            
    
    return 0;
}

