.TH "C:/Users/salaz_000/Desktop/Salazar_Uriel_CSC5_43952/Projects/Project 2/Sorry_v2/build/Debug/Cygwin-Windows Directory Reference" 3 "Mon Jun 8 2015" "Version 2.0" "Sorry!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/salaz_000/Desktop/Salazar_Uriel_CSC5_43952/Projects/Project 2/Sorry_v2/build/Debug/Cygwin-Windows Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.o\&.d\fP"
.br
.in -1c
