.TH "C:/Users/salaz_000/Desktop/Salazar_Uriel_CSC5_43952/Projects/Project 2/Sorry_v2 Directory Reference" 3 "Mon Jun 8 2015" "Version 2.0" "Sorry!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/salaz_000/Desktop/Salazar_Uriel_CSC5_43952/Projects/Project 2/Sorry_v2 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbuild\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.dep\&.inc\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "\fICSC5 Project II\&. \fP"
.in -1c
