.TH "C:/Users/salaz_000/Desktop/Salazar_Uriel_CSC5_43952/Projects/Project 2/Sorry_v2/build/Debug/Cygwin-Windows/main.o.d" 3 "Mon Jun 8 2015" "Version 2.0" "Sorry!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/salaz_000/Desktop/Salazar_Uriel_CSC5_43952/Projects/Project 2/Sorry_v2/build/Debug/Cygwin-Windows/main.o.d \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Sorry! from the source code\&.
